import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase/supabase";
import { CheckoutFormData, Order } from "@/lib/types";
import { sendOrderConfirmationEmail } from "@/utils/email";

// Type without the id field since it will be generated by Supabase
type OrderInsert = Omit<Order, "id">;

export async function POST(request: Request) {
  try {
    // Parse the request body
    const formData: CheckoutFormData = await request.json();

    // Validate required fields
    const requiredFields = [
      "productId",
      "productName",
      "fullName",
      "email",
      "phone",
      "location",
      "city",
    ];

    for (const field of requiredFields) {
      if (!formData[field as keyof CheckoutFormData]) {
        return NextResponse.json(
          { error: `Missing required field: ${field}` },
          { status: 400 }
        );
      }
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(formData.email)) {
      return NextResponse.json(
        { error: "Invalid email format" },
        { status: 400 }
      );
    }

    // Format delivery address
    const deliveryAddress = `${formData.location}, ${formData.city}${
      formData.additionalNotes ? ` (${formData.additionalNotes})` : ""
    }`;

    // Prepare order record - note that we're not including the id field
    const orderRecord: OrderInsert = {
      product_id: formData.productId,
      product_name: formData.productName,
      customer_name: formData.fullName,
      customer_email: formData.email,
      customer_phone: formData.phone,
      delivery_address: deliveryAddress,
      created_at: new Date().toISOString(),
      product_color: formData.color,
      product_size: formData.size,
      price: parseFloat(formData.price),
      delivery_type: formData.deliveryType,
      city: formData.city,
      status: "pending",
    };

    // Insert order into database
    const { data, error } = await supabaseAdmin
      .from("orders")
      .insert(orderRecord)
      .select()
      .single();

    if (error) {
      console.error("Supabase error:", error);
      return NextResponse.json(
        { error: "Failed to create order" },
        { status: 500 }
      );
    }

    // Send email notification (implement this based on your email service)
    try {
      const emailResult = await sendOrderConfirmationEmail(data);
      if (!emailResult.success) {
        console.error("Email sending failed:", emailResult.error);
        // We don't fail the order if email fails, but log it
      }
    } catch (emailError) {
      console.error("Email error:", emailError);
      // We don't fail the order if email fails, but log it
    }

    return NextResponse.json(
      {
        message: "Order submitted successfully",
        orderId: data.id,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Order submission error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
